version: '3'
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - ./docker/postgres/initdb.d:/docker-entrypoint-initdb.d/
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
      - MYSQL_DATABASE=csv
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d/
