name: Build

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "v*"
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: mypassword
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - uses: actions/setup-go@v4
      with:
        go-version: '1.18'
    - name: Install PostgreSQL client
      run: |
        sudo apt-get update
        sudo apt-get install --yes postgresql-client
    - name: Init database
      run: psql -h 127.0.0.1 -d postgres -U postgres  -a -f ./docker/postgres/initdb.d/init.sql
      env:
        PGPASSWORD: mypassword
    - name: Run test
      run: ./scripts/test.sh
    - name: Build
      run: ./scripts/build.sh
    - uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: bin/sql2csv-*
        retention-days: 3
